# Generated by Django 4.2.2 on 2023-07-02 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_created=True)),
                ('file', models.FileField(upload_to='')),
                ('file_type', models.CharField(choices=[('IMG', 'Images'), ('MP4', 'Videos'), ('DOC', 'Documents')], default='IMG', max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('collaborators', models.ManyToManyField(to='collaboration.collaboratormodel')),
            ],
        ),
    ]
